print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
pasta = input("What's your favorite pasta? ")

print(f"So your are {age} old, {height} tall, and {weight} heavy.")
print(f"You like {pasta}.")